<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Windwalker\\Dom\\' => array($vendorDir . '/windwalker/dom'),
    'Asika\\Autolink\\' => array($vendorDir . '/asika/autolink/src'),
    '' => array($baseDir . '/src'),
);
