<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitcb31028c4e024b325862ac382a76240b
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Windwalker\\Dom\\' => 15,
        ),
        'A' => 
        array (
            'Asika\\Autolink\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Windwalker\\Dom\\' => 
        array (
            0 => __DIR__ . '/..' . '/windwalker/dom',
        ),
        'Asika\\Autolink\\' => 
        array (
            0 => __DIR__ . '/..' . '/asika/autolink/src',
        ),
    );

    public static $fallbackDirsPsr4 = array (
        0 => __DIR__ . '/../..' . '/src',
    );

    public static $prefixesPsr0 = array (
        'M' => 
        array (
            'Michelf' => 
            array (
                0 => __DIR__ . '/..' . '/michelf/php-markdown',
            ),
        ),
    );

    public static $classMap = array (
        'S3' => __DIR__ . '/..' . '/tpyo/amazon-s3-php-class/S3.php',
        'S3Exception' => __DIR__ . '/..' . '/tpyo/amazon-s3-php-class/S3.php',
        'S3Request' => __DIR__ . '/..' . '/tpyo/amazon-s3-php-class/S3.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitcb31028c4e024b325862ac382a76240b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitcb31028c4e024b325862ac382a76240b::$prefixDirsPsr4;
            $loader->fallbackDirsPsr4 = ComposerStaticInitcb31028c4e024b325862ac382a76240b::$fallbackDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitcb31028c4e024b325862ac382a76240b::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitcb31028c4e024b325862ac382a76240b::$classMap;

        }, null, ClassLoader::class);
    }
}
